name = "Ark"
uuid = "56664e29-41e4-4ea5-ab0e-825499acc647"
version = "0.3.2"
authors = ["Martin Lange <martin_lange_@gmx.net>", "Adriano Meligrana <adriano.meligrana@centai.eu>"]

[deps]
FieldViews = "ff5a1669-b1f2-423e-bbd7-b7fa0f7e0224"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
ArkMooncakeInterop = "Mooncake"

[compat]
FieldViews = "0.3.2"
FunctionWrappers = "1"
Mooncake = "0.4"
StaticArrays = "1"
julia = "1.10"
